import { zodResolver } from '@hookform/resolvers/zod'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { useState } from 'react'
import { useForm } from 'react-hook-form'
import { z } from 'zod'
import { customersApi, requestsApi, usersApi, type RequestFilters } from '../api/endpoints'
import { useAuth } from '../auth/AuthProvider'
import { PageHeader } from '../components/layout/PageHeader'
import { Badge } from '../components/ui/Badge'
import { Button } from '../components/ui/Button'
import { DataTable } from '../components/ui/DataTable'
import { EmptyState, ErrorState, LoadingState } from '../components/ui/Feedback'
import { Input, Select, Textarea } from '../components/ui/Fields'
import { Modal } from '../components/ui/Modal'
import { customerName, formatDate, matchesText, userEmail } from '../features/shared'
import type { RequestPriority, RequestStatus, ServiceRequest } from '../types/api'

const schema = z.object({ title: z.string().trim().min(1, 'Title is required').max(200), description: z.string().trim().min(1, 'Description is required'), customer_id: z.number().positive('Choose a customer'), status: z.enum(['open', 'in_progress', 'resolved', 'closed']), priority: z.enum(['low', 'medium', 'high']) })
type Values = z.infer<typeof schema>
const statuses: RequestStatus[] = ['open', 'in_progress', 'resolved', 'closed']; const priorities: RequestPriority[] = ['low', 'medium', 'high']
export function ServiceRequestsPage() {
  const { user } = useAuth(); const admin = user?.role === 'admin'; const client = useQueryClient()
  const [filters, setFilters] = useState<RequestFilters>({}); const [search, setSearch] = useState(''); const [editing, setEditing] = useState<ServiceRequest | 'new' | null>(null); const [selected, setSelected] = useState<ServiceRequest | null>(null); const [apiError, setApiError] = useState('')
  const requests = useQuery({ queryKey: ['service-requests', filters], queryFn: () => requestsApi.list(filters) }); const customers = useQuery({ queryKey: ['customers'], queryFn: customersApi.list }); const users = useQuery({ queryKey: ['users'], queryFn: usersApi.list, enabled: admin })
  const { register, handleSubmit, reset, formState: { errors } } = useForm<Values>({ resolver: zodResolver(schema) })
  const refresh = () => { client.invalidateQueries({ queryKey: ['service-requests'] }); client.invalidateQueries({ queryKey: ['dashboard'] }) }
  const save = useMutation({ mutationFn: (values: Values) => editing === 'new' ? requestsApi.create(values) : requestsApi.update((editing as ServiceRequest).id, { title: values.title, description: values.description, status: values.status, priority: values.priority }), onSuccess: () => { refresh(); setEditing(null) }, onError: (error) => setApiError(error.message) })
  const assign = useMutation({ mutationFn: ({ id, agentId }: { id: number; agentId: number | null }) => requestsApi.assign(id, agentId), onSuccess: (data) => { refresh(); setSelected(data) } })
  const remove = useMutation({ mutationFn: requestsApi.remove, onSuccess: () => { refresh(); setSelected(null) } })
  const openForm = (request: ServiceRequest | 'new') => { setApiError(''); setEditing(request); reset(request === 'new' ? { title: '', description: '', customer_id: 0, status: 'open', priority: 'medium' } : request) }
  const visible = requests.data?.filter((item) => matchesText(item, search)) ?? []
  return <div className="page"><PageHeader eyebrow="Workflow" title="Service requests" description="Track, prioritize, and resolve customer work." action={<Button onClick={() => openForm('new')}>New request</Button>} />
    <section className="filter-bar"><Input label="Search displayed results" value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Title or description" /><Select label="Status" value={filters.status ?? ''} onChange={(e) => setFilters({ ...filters, status: e.target.value as RequestStatus || undefined })}><option value="">All statuses</option>{statuses.map((value) => <option key={value} value={value}>{value.replace('_', ' ')}</option>)}</Select><Select label="Priority" value={filters.priority ?? ''} onChange={(e) => setFilters({ ...filters, priority: e.target.value as RequestPriority || undefined })}><option value="">All priorities</option>{priorities.map((value) => <option key={value}>{value}</option>)}</Select><Select label="Customer" value={filters.customer_id ?? ''} onChange={(e) => setFilters({ ...filters, customer_id: e.target.value ? Number(e.target.value) : undefined })}><option value="">All customers</option>{customers.data?.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</Select>{admin && <Select label="Assignee" value={filters.assigned_agent_id ?? ''} onChange={(e) => setFilters({ ...filters, assigned_agent_id: e.target.value ? Number(e.target.value) : undefined })}><option value="">All assignees</option>{users.data?.filter((item) => item.role === 'agent').map((item) => <option key={item.id} value={item.id}>{item.email}</option>)}</Select>}</section>
    {requests.isLoading || customers.isLoading ? <LoadingState /> : requests.isError ? <ErrorState error={requests.error} retry={() => requests.refetch()} /> : !visible.length ? <EmptyState title="No matching requests" message="Change the filters or create a new request." /> : <DataTable headers={['Request', 'Customer', 'Status', 'Priority', 'Assignee', 'Updated', 'Actions']}>{visible.map((request) => <tr key={request.id}><td><button className="link-button" onClick={() => setSelected(request)}>{request.title}</button><small className="table-subline">#{request.id}</small></td><td>{customerName(customers.data, request.customer_id)}</td><td><Badge value={request.status} /></td><td><Badge value={request.priority} /></td><td>{userEmail(users.data, request.assigned_agent_id, request.assigned_agent_email)}</td><td className="muted">{formatDate(request.updated_at)}</td><td><div className="row-actions"><Button variant="ghost" onClick={() => setSelected(request)}>Details</Button><Button variant="secondary" onClick={() => openForm(request)}>Edit</Button>{admin && <Button variant="danger" onClick={() => { if (confirm(`Delete request “${request.title}”?`)) remove.mutate(request.id) }}>Delete</Button>}</div></td></tr>)}</DataTable>}
    {editing && <Modal title={editing === 'new' ? 'Create service request' : 'Edit service request'} onClose={() => setEditing(null)}><form className="form-stack" onSubmit={handleSubmit((values) => save.mutate(values))}>{apiError && <div className="alert" role="alert">{apiError}</div>}<Input label="Title" error={errors.title?.message} {...register('title')} /><Textarea label="Description" rows={5} error={errors.description?.message} {...register('description')} /><Select label="Customer" disabled={editing !== 'new'} error={errors.customer_id?.message} {...register('customer_id', { valueAsNumber: true })}><option value={0}>Choose a customer</option>{customers.data?.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</Select><div className="form-grid"><Select label="Status" {...register('status')}>{statuses.map((value) => <option key={value} value={value}>{value.replace('_', ' ')}</option>)}</Select><Select label="Priority" {...register('priority')}>{priorities.map((value) => <option key={value}>{value}</option>)}</Select></div><div className="modal-actions"><Button type="button" variant="secondary" onClick={() => setEditing(null)}>Cancel</Button><Button type="submit" disabled={save.isPending}>{save.isPending ? 'Saving…' : 'Save request'}</Button></div></form></Modal>}
    {selected && <Modal title="Request details" onClose={() => setSelected(null)}><div className="detail-title"><div><span className="eyebrow">Request #{selected.id}</span><h3>{selected.title}</h3></div><Badge value={selected.priority} /></div><p className="description">{selected.description}</p><dl className="details"><div><dt>Customer</dt><dd>{customerName(customers.data, selected.customer_id)}</dd></div><div><dt>Status</dt><dd><Badge value={selected.status} /></dd></div><div><dt>Assigned to</dt><dd>{userEmail(users.data, selected.assigned_agent_id, selected.assigned_agent_email)}</dd></div><div><dt>Updated</dt><dd>{formatDate(selected.updated_at)}</dd></div></dl>{admin && <label className="field"><span>Assign active agent</span><select value={selected.assigned_agent_id ?? ''} onChange={(e) => assign.mutate({ id: selected.id, agentId: e.target.value ? Number(e.target.value) : null })}><option value="">Unassigned</option>{users.data?.filter((item) => item.role === 'agent' && item.is_active).map((item) => <option key={item.id} value={item.id}>{item.email}</option>)}</select></label>}<div className="modal-actions"><Button variant="secondary" onClick={() => { setSelected(null); openForm(selected) }}>Edit</Button><Button onClick={() => setSelected(null)}>Done</Button></div></Modal>}
  </div>
}
